"""Project-wide scalar constants."""

DEFAULT_K = 11
BASE_INTERVAL_MINUTES = 5

TRADING_DAYS_PER_YEAR = 252
TRADING_HOURS_PER_DAY = 24
PERIODS_PER_HOUR = TRADING_HOURS_PER_DAY * 60 // BASE_INTERVAL_MINUTES

SHUFFLE_SEED = 137
GAUSSIAN_SEED = 271
